import React from "react";
import { SEOHead } from "@/components/SEOHead";
import { motion } from "framer-motion";

export function PrivacyPolicyPage() {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full pt-32 pb-24 bg-background"
    >
      <SEOHead title="Privacy Policy" description="Webco Privacy Policy and data handling practices." />
      
      <div className="container mx-auto px-4 md:px-6 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold font-serif mb-8 text-foreground">Privacy Policy</h1>
        <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-foreground mt-8 mb-4 font-bold text-2xl">1. Introduction</h2>
          <p>
            Welcome to Webco. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.
          </p>

          <h2 className="text-foreground mt-8 mb-4 font-bold text-2xl">2. The Data We Collect About You</h2>
          <p>
            We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li><strong>Identity Data</strong> includes first name, last name, username or similar identifier.</li>
            <li><strong>Contact Data</strong> includes billing address, delivery address, email address and telephone numbers.</li>
            <li><strong>Technical Data</strong> includes internet protocol (IP) address, your login data, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform, and other technology on the devices you use to access this website.</li>
            <li><strong>Usage Data</strong> includes information about how you use our website, products and services.</li>
          </ul>

          <h2 className="text-foreground mt-8 mb-4 font-bold text-2xl">3. How We Use Your Data in AI Systems</h2>
          <p>
            As an AI agency, we process client data to build and train custom models. We enforce strict data boundaries:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Your proprietary business data is <strong>never</strong> used to train public foundation models.</li>
            <li>Chat transcripts generated by end-users interacting with your custom bots are stored securely and made available only to authorized personnel within your organization.</li>
            <li>We utilize zero-retention API agreements with providers like OpenAI and Anthropic where applicable.</li>
          </ul>

          <h2 className="text-foreground mt-8 mb-4 font-bold text-2xl">4. Data Security</h2>
          <p>
            We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorized way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know. They will only process your personal data on our instructions and they are subject to a duty of confidentiality.
          </p>

          <h2 className="text-foreground mt-8 mb-4 font-bold text-2xl">5. Contact Details</h2>
          <p>
            If you have any questions about this privacy policy or our privacy practices, please contact us at:<br/>
            Email: sanudiashi999@gmail.com<br/>
            Phone: +91 8101445973
          </p>
        </div>
      </div>
    </motion.div>
  );
}

export default PrivacyPolicyPage;
